export const GET_DAY = "GET_DAY";
export const GET_ALL_DAYS = "GET_ALL_DAYS";
export const GET_MEDICATION_OPTS = "GET_MEDICATION_OPTS";
export const GET_DRINK_OPTS = "GET_DRINK_OPTS";
export const GET_FOOD_TAGS = "GET_FOOD_TAGS";

export const CREATE_DAY = "CREATE_DAY";
export const CREATE_TEXT_SUCCESS = "CREATE_TEXT_SUCCESS";
export const CREATE_PHOTO_SUCCESS = "CREATE_PHOTO_SUCCESS";

export const DELETE_PHOTO_SUCCESS = "DELTE_PHOTO_SUCCESS";
export const DELETE_TEXT_SUCCESS = "DELTE_TEXT_SUCCESS";
export const DELETE_MEDICATION_SUCCESS = "DELTE_MEDICATION_SUCCESS";
export const DELETE_DRINK_SUCCESS = "DELTE_DRINK_SUCCESS";
export const DELETE_FOOD_SUCCESS = "DELTE_FOOD_SUCCESS";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const SELECT_DATE = "SELECT_DATE";
