export const GET_DAY = "GET_DAY";
export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const GET_MEDICATION_OPTS = "GET_MEDICATION_OPTS";
export const GET_DRINK_OPTS = "GET_DRINK_OPTS";
export const CREATE_COLLECTION = "CREATE_COLLECTION";
export const CREATE_TEXT_SUCCESS = "CREATE_TEXT_SUCCESS";
export const CREATE_PHOTO_SUCCESS = "CREATE_PHOTO_SUCCESS";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const SELECT_DATE = "SELECT_DATE";
